-- Migration : boîte aux lettres des ordres serveur → borne (set_mode, watch_on,
-- watch_off). Le daemon la consulte en poll sortant (~3 s) puis ACK.
-- Sur base neuve : déjà inclus via schema.sql (IF NOT EXISTS, rejouable).
-- Sur base existante : psql -f database/migration_borne_commandes.sql
CREATE TABLE IF NOT EXISTS public.borne_commandes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    device_id character varying(50) NOT NULL DEFAULT '*',
    type character varying(20) NOT NULL CHECK (type IN ('set_mode','watch_on','watch_off')),
    payload text NOT NULL DEFAULT '{}',
    statut character varying(20) NOT NULL DEFAULT 'pending' CHECK (statut IN ('pending','acked','superseded')),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_borne_cmd_pending ON public.borne_commandes USING btree (device_id, statut, id);
