-- Journal d'audit — requis par api/biometric.php (auditLog) et api/borne_pointage.php.
-- À appliquer sur Supabase (SQL editor / psql) : absente = pointages borne en échec.
CREATE TABLE IF NOT EXISTS public.journal_audit (
  id_audit                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_utilisateur             integer NULL REFERENCES utilisateurs_systeme(id_utilisateur) ON DELETE SET NULL,
  action                     character varying(60) NOT NULL,
  table_concernee            character varying(60) NULL,
  id_enregistrement_concerne integer NULL,
  details                    text NULL,
  date_heure                 timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_audit_date ON public.journal_audit USING btree (date_heure) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_audit_utilisateur ON public.journal_audit USING btree (id_utilisateur) TABLESPACE pg_default;
