-- MADA Digital — STRUCTURE (dump Supabase public, 2026-09-29 15:51)
-- Source : base live. Restauration : psql -f schema.sql puis psql -f data.sql
-- Ordre topologique (parents avant enfants) pour creation sur base vide.

CREATE TABLE IF NOT EXISTS public.appareils_pointage (
    id_appareil integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom_appareil character varying(100) NOT NULL,
    emplacement character varying(150),
    type_capteur character varying(30) NOT NULL,
    adresse_ip character varying(45),
    statut character varying(20) NOT NULL DEFAULT 'actif'::character varying,
    derniere_connexion timestamp without time zone,
    PRIMARY KEY (id_appareil)
);

CREATE SEQUENCE IF NOT EXISTS public.biometric_slots_id_seq;
CREATE TABLE IF NOT EXISTS public.biometric_slots (
    id integer NOT NULL DEFAULT nextval('public.biometric_slots_id_seq'::regclass),
    id_employe integer NOT NULL,
    device_id character varying(50) NOT NULL DEFAULT 'r307_main'::character varying,
    slot_number smallint NOT NULL,
    empreinte_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CHECK (((slot_number >= 0) AND (slot_number <= 999))),
    UNIQUE (id_employe),
    UNIQUE (device_id, slot_number)
);
ALTER SEQUENCE public.biometric_slots_id_seq OWNED BY public.biometric_slots.id;
CREATE INDEX IF NOT EXISTS idx_slots_device ON public.biometric_slots USING btree (device_id, slot_number);

CREATE TABLE IF NOT EXISTS public.departements (
    id_departement integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom_departement character varying(100) NOT NULL,
    description text,
    PRIMARY KEY (id_departement)
);

CREATE TABLE IF NOT EXISTS public.employes (
    id_employe integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    matricule character varying(20) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    email character varying(150),
    telephone character varying(30),
    id_departement integer,
    poste character varying(100),
    date_embauche date,
    statut character varying(20) NOT NULL DEFAULT 'actif'::character varying,
    photo_profil character varying(255),
    PRIMARY KEY (id_employe),
    FOREIGN KEY (id_departement) REFERENCES public.departements(id_departement) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (matricule),
    UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_employes_departement ON public.employes USING btree (id_departement);
CREATE INDEX IF NOT EXISTS idx_employes_statut ON public.employes USING btree (statut);

CREATE TABLE IF NOT EXISTS public.heures_mensuelles (
    id_employe integer NOT NULL,
    mois date NOT NULL,
    total_secondes integer NOT NULL DEFAULT 0,
    nb_pointages integer NOT NULL DEFAULT 0,
    calcule_le timestamp without time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id_employe, mois)
);

CREATE TABLE IF NOT EXISTS public.historique_pointages (
    id_pointage integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_uuid_local uuid NOT NULL,
    id_employe integer NOT NULL,
    id_appareil integer,
    type_pointage character varying(20) NOT NULL,
    date_heure timestamp without time zone NOT NULL,
    methode_verification character varying(20) NOT NULL,
    score_correspondance numeric(5,2),
    source_donnee character varying(20) NOT NULL DEFAULT 'serveur'::character varying,
    synchronise boolean NOT NULL DEFAULT true,
    date_synchronisation timestamp without time zone,
    statut character varying(20) NOT NULL DEFAULT 'valide'::character varying,
    commentaire text,
    archived_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id_pointage),
    UNIQUE (id_uuid_local)
);
CREATE INDEX IF NOT EXISTS historique_pointages_id_appareil_idx ON public.historique_pointages USING btree (id_appareil);
CREATE INDEX IF NOT EXISTS historique_pointages_id_employe_idx ON public.historique_pointages USING btree (id_employe);
CREATE INDEX IF NOT EXISTS historique_pointages_date_heure_idx ON public.historique_pointages USING btree (date_heure);
CREATE INDEX IF NOT EXISTS historique_pointages_statut_idx ON public.historique_pointages USING btree (statut);
CREATE INDEX IF NOT EXISTS historique_pointages_synchronise_idx ON public.historique_pointages USING btree (synchronise);

CREATE TABLE IF NOT EXISTS public.horaires_travail (
    id_horaire integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nom_horaire character varying(100) NOT NULL,
    heure_debut time without time zone NOT NULL,
    heure_fin time without time zone NOT NULL,
    jours_travail character varying(50) NOT NULL,
    tolerance_retard_min integer NOT NULL DEFAULT 10,
    PRIMARY KEY (id_horaire)
);

CREATE TABLE IF NOT EXISTS public.pointages (
    id_pointage integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_uuid_local uuid NOT NULL,
    id_employe integer NOT NULL,
    id_appareil integer,
    type_pointage character varying(20) NOT NULL,
    date_heure timestamp without time zone NOT NULL,
    methode_verification character varying(20) NOT NULL,
    score_correspondance numeric(5,2),
    source_donnee character varying(20) NOT NULL DEFAULT 'serveur'::character varying,
    synchronise boolean NOT NULL DEFAULT true,
    date_synchronisation timestamp without time zone,
    statut character varying(20) NOT NULL DEFAULT 'valide'::character varying,
    commentaire text,
    PRIMARY KEY (id_pointage),
    FOREIGN KEY (id_appareil) REFERENCES public.appareils_pointage(id_appareil) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_employe) REFERENCES public.employes(id_employe) ON UPDATE CASCADE,
    UNIQUE (id_uuid_local)
);
CREATE INDEX IF NOT EXISTS idx_pointages_date ON public.pointages USING btree (date_heure);
CREATE INDEX IF NOT EXISTS idx_pointages_appareil ON public.pointages USING btree (id_appareil);
CREATE INDEX IF NOT EXISTS idx_pointages_employe ON public.pointages USING btree (id_employe);
CREATE INDEX IF NOT EXISTS idx_pointages_statut ON public.pointages USING btree (statut);
CREATE INDEX IF NOT EXISTS idx_pointages_synchronise ON public.pointages USING btree (synchronise);

CREATE TABLE IF NOT EXISTS public.utilisateurs_systeme (
    id_utilisateur integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    matricule character varying(20) NOT NULL,
    nom character varying(100),
    prenom character varying(100),
    telephone character varying(30),
    id_departement integer,
    email character varying(150) NOT NULL,
    mot_de_passe_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    statut character varying(20) NOT NULL DEFAULT 'actif'::character varying,
    derniere_connexion timestamp without time zone,
    PRIMARY KEY (id_utilisateur),
    FOREIGN KEY (id_departement) REFERENCES public.departements(id_departement) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (email),
    UNIQUE (matricule)
);

CREATE TABLE IF NOT EXISTS public.donnees_biometriques (
    id_biometrie integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_employe integer NOT NULL,
    type_biometrie character varying(20) NOT NULL,
    gabarit_chiffre bytea NOT NULL,
    algorithme character varying(50),
    id_appareil_enrolement integer,
    date_enregistrement timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_expiration timestamp without time zone,
    statut character varying(20) NOT NULL DEFAULT 'actif'::character varying,
    PRIMARY KEY (id_biometrie),
    FOREIGN KEY (id_appareil_enrolement) REFERENCES public.appareils_pointage(id_appareil) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_employe) REFERENCES public.employes(id_employe) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_biometrie_appareil ON public.donnees_biometriques USING btree (id_appareil_enrolement);
CREATE INDEX IF NOT EXISTS idx_biometrie_employe ON public.donnees_biometriques USING btree (id_employe);
CREATE INDEX IF NOT EXISTS idx_biometrie_type ON public.donnees_biometriques USING btree (type_biometrie);

CREATE TABLE IF NOT EXISTS public.journal_audit (
    id_audit integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_utilisateur integer,
    action character varying(60) NOT NULL,
    table_concernee character varying(60),
    id_enregistrement_concerne integer,
    details text,
    date_heure timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_audit),
    FOREIGN KEY (id_utilisateur) REFERENCES public.utilisateurs_systeme(id_utilisateur) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_date ON public.journal_audit USING btree (date_heure);
CREATE INDEX IF NOT EXISTS idx_audit_utilisateur ON public.journal_audit USING btree (id_utilisateur);

CREATE TABLE IF NOT EXISTS public.borne_etat (
    device_id character varying(50) NOT NULL,
    last_seen timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    empreintes integer NOT NULL DEFAULT 0,
    hw_ok boolean,
    watching boolean NOT NULL DEFAULT false,
    PRIMARY KEY (device_id)
);

CREATE TABLE IF NOT EXISTS public.borne_commandes (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    device_id character varying(50) NOT NULL DEFAULT '*',
    type character varying(20) NOT NULL CHECK (type IN ('set_mode','watch_on','watch_off')),
    payload text NOT NULL DEFAULT '{}',
    statut character varying(20) NOT NULL DEFAULT 'pending' CHECK (statut IN ('pending','acked','superseded')),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_borne_cmd_pending ON public.borne_commandes USING btree (device_id, statut, id);

-- Dernier événement détection (widget d'un autre appareil) : rejouable,
-- db-init rejoue schema.sql à chaque déploiement (base existante incluse).
ALTER TABLE public.borne_etat ADD COLUMN IF NOT EXISTS last_seq integer;
ALTER TABLE public.borne_etat ADD COLUMN IF NOT EXISTS last_detection timestamp without time zone;
ALTER TABLE public.borne_etat ADD COLUMN IF NOT EXISTS last_result jsonb;

CREATE OR REPLACE FUNCTION public.archive_pointages()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  moved INTEGER;
BEGIN
  INSERT INTO historique_pointages
  SELECT *, NOW() FROM pointages
  WHERE date_heure::date < CURRENT_DATE;

  GET DIAGNOSTICS moved = ROW_COUNT;
  DELETE FROM pointages WHERE date_heure::date < CURRENT_DATE;
  RETURN moved;
END;
$function$;

