<?php
// Toggle de la surveillance du capteur (détection continue en mode pointage).
// GET  : état courant (daemon + flags) — pour l'état initial du bouton.
// POST {enabled: bool} : watch-on/watch-off sur le daemon (le démarre si absent).
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/../app/Core/Biometric/FingerprintReader.php';
require_once __DIR__ . '/../app/Core/Biometric/SdkReader.php';
require_once __DIR__ . '/../app/Core/Biometric/R307Supervisor.php';

use App\Core\Biometric\R307Supervisor;
use App\Core\Biometric\SdkReader;

$method = $_SERVER['REQUEST_METHOD'];
if (!in_array($method, ['GET', 'POST'], true)) {
    http_response_code(405);
    echo json_encode(['ok' => false, 'message' => 'Méthode non autorisée']);
    exit;
}
if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(['ok' => false, 'message' => 'Non authentifié']);
    exit;
}

// Lecture seule en GET ; écriture réservée Super Admin en POST.
if ($method === 'POST' && !in_array($_SESSION['role'] ?? '', ['super_admin', 'admin_systeme'], true)) {
    http_response_code(403);
    echo json_encode(['ok' => false, 'message' => 'Seul Super Admin peut activer/désactiver la surveillance']);
    exit;
}

try {
    // URL du daemon configurable (R307_SERVICE_URL) : 127.0.0.1 en local XAMPP,
    // host.docker.internal:8765 en pont Docker vers le daemon Windows.
    $serviceUrl = rtrim(getenv('R307_SERVICE_URL') ?: 'http://127.0.0.1:8765', '/');
    $svcHost = strtolower((string)(parse_url($serviceUrl, PHP_URL_HOST) ?? ''));
    $isLocal = in_array($svcHost, ['127.0.0.1', 'localhost', '::1', '[::1]'], true);
    $pdo = getDB();
    // Filet distant : si le daemon est injoignable en direct (VPS sans pont),
    // l'ordre est déposé en BDD et appliqué au prochain poll (~3 s).
    $queueRemote = function(string $type) use ($pdo): bool {
        try {
            $pdo->exec("CREATE TABLE IF NOT EXISTS public.borne_commandes (
                id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                device_id character varying(50) NOT NULL DEFAULT '*',
                type character varying(20) NOT NULL CHECK (type IN ('set_mode','watch_on','watch_off')),
                payload text NOT NULL DEFAULT '{}',
                statut character varying(20) NOT NULL DEFAULT 'pending' CHECK (statut IN ('pending','acked','superseded')),
                created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id))");
            $pdo->prepare("UPDATE borne_commandes SET statut='superseded' WHERE device_id='*' AND type=? AND statut='pending'")->execute([$type]);
            $pdo->prepare("INSERT INTO borne_commandes (device_id, type, payload, statut) VALUES ('*',?,'{}','pending')")->execute([$type]);
            return true;
        } catch (Throwable $e) { error_log('sensor_watch commande: '.$e->getMessage()); return false; }
    };
    $daemonCall = function(string $path, string $method = 'GET', int $timeout = 8) use ($serviceUrl) {
        $ctx = stream_context_create(['http' => [
            'method' => $method,
            'header' => "Content-Type: application/json\r\n",
            'content' => $method === 'POST' ? '{}' : null,
            'timeout' => $timeout,
            'ignore_errors' => true,
        ]]);
        $resp = @file_get_contents($serviceUrl . $path, false, $ctx);
        if ($resp === false) return null;
        $data = json_decode((string)$resp, true);
        return is_array($data) ? $data : null;
    };

    if ($method === 'GET') {
        $status = $daemonCall('/status', 'GET', 4);
        // État distant désiré vs appliqué (borne sans lien direct).
        $remote = ['desired' => null, 'applied' => true];
        try {
            $d = $pdo->query("SELECT id, type FROM borne_commandes WHERE device_id='*' AND type IN ('watch_on','watch_off') ORDER BY id DESC LIMIT 1")->fetch();
            if ($d) {
                $a = $pdo->query("SELECT id FROM borne_commandes WHERE device_id='*' AND type IN ('watch_on','watch_off') AND statut='acked' ORDER BY id DESC LIMIT 1")->fetch();
                $remote = ['desired' => ($d['type'] === 'watch_on' ? 'on' : 'off'),
                    'applied' => ($a && (int)$a['id'] >= (int)$d['id'])];
            }
        } catch (Throwable $e) {}
        if ($status === null) {
            // Daemon absent : le bouton démarre sur "inactif".
            echo json_encode([
                'ok' => true,
                'daemon_up' => false,
                'watching' => false,
                'watch_user_enabled' => false,
                'watch_enabled' => false,
                'remote' => $remote,
                'message' => 'Service de surveillance arrêté',
            ]);
            exit;
        }
        echo json_encode([
            'ok' => true,
            'daemon_up' => true,
            'watching' => (bool)($status['watching'] ?? false),
            'watch_user_enabled' => (bool)($status['watch_user_enabled'] ?? true),
            'watch_enabled' => (bool)($status['watch_enabled'] ?? false),
            'last_detection' => $status['last_detection'] ?? null,
            'last_result' => $status['last_result'] ?? null,
            'remote' => $remote,
            'message' => 'ok',
        ]);
        exit;
    }

    // ── POST : toggle ──
    $input = getJsonInput();
    $enabled = !empty($input['enabled']);
    $modeFile = __DIR__ . '/../python/mode.json';
    $mode = 'pointage';
    if (is_file($modeFile)) {
        $j = json_decode((string)@file_get_contents($modeFile), true);
        if (is_array($j) && !empty($j['mode'])) $mode = (string)$j['mode'];
    }

    if ($enabled) {
        // Le daemon doit tourner pour accepter watch-on en direct.
        $directPossible = true;
        $unreachableMsg = '';
        if ($isLocal) {
            // Local : on peut le démarrer nous-mêmes s'il est absent.
            $ensure = R307Supervisor::ensureRunning();
            if (!$ensure['up']) { $directPossible = false; $unreachableMsg = $ensure['message']; }
        } else {
            // Pont distant (ex. Docker → daemon Windows) : pas de spawn local,
            // on vérifie juste qu'il répond.
            $probe = $daemonCall('/status', 'GET', 4);
            if ($probe === null) { $directPossible = false; $unreachableMsg = 'Daemon injoignable sur ' . $serviceUrl . ' — lancez-le sur le PC du capteur'; }
        }
        if (!$directPossible) {
            // Filet distant (VPS sans pont / borne sur PC Windows) : l'ordre est
            // déposé en BDD et appliqué par la borne au prochain poll (~3 s).
            if ($queueRemote('watch_on')) {
                echo json_encode(['ok'=>true,'watching'=>false,'watch_user_enabled'=>true,
                    'queued'=>true,'mode'=>$mode,
                    'message'=>'Ordre enregistré — appliqué par la borne (~3 s)']);
                exit;
            }
            http_response_code(503);
            echo json_encode(['ok' => false, 'message' => $unreachableMsg]);
            exit;
        }
        $data = $daemonCall('/watch-on', 'POST', 8);
        if (!is_array($data) || empty($data['ok'])) {
            // Daemon injoignable en direct (VPS sans pont) : file distant.
            if ($queueRemote('watch_on')) {
                echo json_encode(['ok'=>true,'watching'=>false,'watch_user_enabled'=>true,
                    'queued'=>true,'mode'=>$mode,
                    'message'=>'Ordre enregistré — appliqué par la borne (~3 s)']);
                exit;
            }
            http_response_code(500);
            echo json_encode(['ok'=>false,
                'message'=>$data['message'] ?? 'Daemon injoignable pour watch-on']);
            exit;
        }
        echo json_encode([
            'ok' => true,
            'watching' => (bool)($data['watching'] ?? false),
            'watch_user_enabled' => true,
            'mode' => $mode,
            'message' => $mode === 'pointage'
                ? 'Surveillance activée — le capteur scrute en continu'
                : 'Surveillance armée — elle démarre au retour en mode pointage',
        ]);
        exit;
    }

    // watch-off : le daemon peut être arrêté — c'est un no-op réussi côté UI.
    $data = $daemonCall('/watch-off', 'POST', 4);
    $daemonAck = is_array($data) && !empty($data['ok']);
    if (!$daemonAck) $queueRemote('watch_off'); // filet distant (VPS sans pont)
    echo json_encode([
        'ok' => true,
        'watching' => false,
        'watch_user_enabled' => false,
        'daemon_ack' => $daemonAck,
        'message' => $daemonAck ? 'Surveillance désactivée' : 'Surveillance désactivée (service arrêté)',
    ]);
} catch (Throwable $e) {
    error_log('sensor_watch: ' . $e->getMessage());
    http_response_code(500);
    echo json_encode(['ok' => false, 'message' => $e->getMessage()]);
}
